CREATE TABLE customer (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fullname VARCHAR(255),
  email VARCHAR(255) UNIQUE,
  contactNumber VARCHAR(255),
  lastUpdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE payment (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customerId INT,
  value INT,
  date DATE,
  FOREIGN KEY (customerId) REFERENCES customer(id),
  lastUpdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
